Version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:sudo pip install jupyter
      - run:sudo pip install numpy
      - run:sudo pip install matplotlib
      - run:sudo pip install sklearn
      - run:sudo pip install nbconvert
      - run:jupyter-nbconvert --execute HomeWork1.ipunb

      - store_artifacts:
         path: ./HomeWork1.html

